services:
  web:
    build:
      context: .
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: check_master_db
      MYSQL_USER: check_master_user
      MYSQL_PASSWORD: check_master_password
    
    ports:
      - "3306:3306"
    volumes:
      - ./storage/data/check_master_db.sql:/docker-entrypoint-initdb.d/check_master_db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  db_data:
